name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Create .env file
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_REDIRECT_URL: ${{ secrets.SPOTIFY_REDIRECT_URL }}
        run: |
          if [ -n "$SPOTIFY_CLIENT_ID" ]; then
            echo "SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID" >> .env
            echo "SPOTIFY_REDIRECT_URL=$SPOTIFY_REDIRECT_URL" >> .env
          else
            echo "Warning: Secrets not found, skipping .env creation"
          fi

      - name: Get Dependencies
        run: flutter pub get

      # - name: Build Android APK
      #   env:
      #     KEY_ALIAS: ${{ secrets.KeyAlias }}
      #     KEY_PASSWORD: ${{ secrets.KeyPassword }}
      #     STORE_PASSWORD: ${{ secrets.StorePassword }}
      #     KEYSTORE_PATH: android/app/upload-keystore.jks
      #   run: |
      #     echo "${{ secrets.ReviewKeystore }}" | base64 --decode > android/app/upload-keystore.jks
      #     flutter build apk --release

      # --- iOS Build (Unsigned) ---
      - name: Build iOS App (Unsigned)
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r Runner.ipa Payload
          rm -rf Payload

      # --- Rename for Clarity ---
      - name: Rename Artifacts
        run: |
          mv build/ios/iphoneos/Runner.ipa ./qr-music-player-ios-unsigned.ipa

      # --- Create Release ---
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qr-music-player-ios-unsigned.ipa
